name: Non-Critical Instance App monitor rule
type: metric_aggregation

#es_host: localhost
#es_port: 9200

index: heartbeat*

buffer_time:
  minutes: 20
realert:
  minutes: 20

metric_agg_key: summary.down
metric_agg_type: avg
query_key: instance-tag
#doc_type: metricsets

bucket_interval:
  minutes: 20

sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

#min_threshold: 0.1
max_threshold: 0.9

match_enhancements:
- "elastalert_modules.tst_ist_tz_enhancement.ConvertTzInfo"

filter:
- term:
    critical-instance: false

# (Required)
# The alert is use when a match is found
alert: "elastalert_modules.slack_custom_alert.SlackCustomAlert"

slack_webhook_url: ""
slack_title: "CSAD IT - Non Critical Instance Application Health Monitoring Alarm"
